---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-feature-build
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: push-feature-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    tags: ${DRONE_BRANCH/\//-}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - "*/*"
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: qzi9PHVqCMMpor0NmXBZdlni4s3Mh/p92sGSeEBzSaPBdrImoAzPmA==
---
kind: secret
name: docker_password
data: YffaIZ+2gQtGkbyFiqpj5MV2gaVQ+GaYQ5CRtjrF4545rPnzZho2RD/rH1XG+L5+jGqg3e7JynrabDhmkSn5rQ==
---
kind: signature
hmac: 37e49818e5e8e51cf40bb148972eb998cda64e7221a0dc161895c80c06e86956

...
